workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Instalar dependências Flutter
        script: flutter pub get
      - name: Instalar dependências CocoaPods
        script: |
          cd ios
          pod install
      - name: Build do IPA
        script: |
          flutter build ipa --release --export-method=app-store
    artifacts:
      - build/ios/ipa/*.ipa