const String termsOfUse =
    '''A seguir estão descritas as regras aplicáveis à utilização da Plataforma Cocatrel disponibilizada pela Cooperativa dos Cafeicultores da Zona de Três Pontas - Ltda. - Cocatrel, cooperativa com sede em Três Pontas – MG, situada na Rua Bento de Brito, n.º 110, CEP:37.190-000, inscrita no CNPJ/MF sob o n.º 25.266.685/0001-43, daqui em diante “Cocatrel”, aos seus “Usuários da Plataforma” para uso em dispositivos móveis.

A Cocatrel declara que possui infraestrutura tecnológica de ponta para atender as demandas de Sistema e aplicação de Tecnologia da Informação, contando com o suporte de técnicos devidamente capacitados e autorizados, para prestar suporte a eventuais problemas que envolva o uso do aplicativo.

A Plataforma da Cocatrel permite que o Usuário acesse informações a conteúdos relacionados ao Portal do Cooperado.

Ao acessar a Plataforma, o Usuário se submeterá, de forma automática, às regras e condições deste Termo de Uso da Plataforma e da Política de Privacidade. Essa, elaborada pela Cocatrel, de acordo com seu Estatuto Social e com base nos requisitos de segurança da informação, consoante a Lei de Proteção de Dados (Lei 13.709).''';

const String termsOfUseToDialog =
    '''O presente cadastramento é pessoal, devendo ser feito pelo próprio cooperado, sendo proibida a realização por terceiros. Para tanto, será obrigatório o preenchimento correto e completo dos dados pessoais abaixo (que deverão corresponder, fielmente, aos dados constantes na ficha de matrícula do cooperado), com intuito de se atestar a identidade do responsável pelo cadastramento.

Havendo confirmação dos dados acima o cooperado receberá no e-mail cadastrado no sistema da cooperativa, sua senha para acesso ao portal. Para o aplicativo, será a senha e o PIN escolhido pelo usuário, no ato do cadastro.  Além disso, declara estar plenamente ciente que todas as “operações” a serem disponibilizadas através do “portal do cooperado”, e do Aplicativo, somente serão efetivadas mediante o uso da “senha pessoal” e “PIN” (que será gerada automaticamente, para o portal, após a finalização do cadastro eletrônico, podendo ser substituída, posteriormente, pelo cooperado); ressaltando-se que tal “senha pessoal” e “PIN” substituirá a sua assinatura nas respectivas transações, devendo, portanto, ser utilizada apenas por ele, sendo de sua inteira e exclusiva responsabilidade a guarda e o sigilo das mesmas.  Declara, também, que, na hipótese de ocorrer quaisquer fatos que, de alguma forma, possam vir a comprometer o sigilo da “senha pessoal” e “PIN” por ele cadastrados, se compromete a comunicar imediatamente à COCATREL e à Cocatrel Coffee Pay, para que possa ser providenciado o eventual cancelamento de tal “senha pessoal” e “PIN”. anteriormente cadastradas e a substituição por outras novas e diferentes.  Declara, ainda, que tem conhecimento que as “informações” e “relatórios” disponibilizados pelo “portal do cooperado” e “Aplicativo” estão sujeitos a eventuais erros/imprecisões, devendo, em caso de dúvida, o respectivo conteúdo ser confirmado no “departamento responsável”.  Declara, outrossim, que está de acordo que todas os pagamentos relacionados a transações feitas pelo portal do cooperado serão efetivados apenas através de depósito/transferência bancária em conta (previamente cadastrada).  Declara, por fim, que tem ciência que as transações realizadas no portal e aplicativo são monitoradas pela COCATREL, e Cocatrel Coffee Pay podendo, a qualquer momento, ser bloqueado o respectivo acesso se houver suspeita de mau uso ou tentativa de utilização irregular por terceiros.''';
