org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35
android.builtInKotlin=false

# Substitua a linha anterior 'android.newDsl=false' por estas duas:
android.newDsl=false
android.experimental.disableNewDslInterface=true